<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'DrydockWindowsAlmanacServiceHostBlueprintImplementation' => 'drydock/DrydockWindowsAlmanacServiceHostBlueprintImplementation.php',
    'DrydockWindowsSSHCommandInterface' => 'drydock/DrydockWindowsSSHCommandInterface.php',
    'DrydockWindowsWorkingCopyBlueprintImplementation' => 'drydock/DrydockWindowsWorkingCopyBlueprintImplementation.php',
  ),
  'function' => array(),
  'xmap' => array(
    'DrydockWindowsAlmanacServiceHostBlueprintImplementation' => 'DrydockBlueprintImplementation',
    'DrydockWindowsSSHCommandInterface' => 'DrydockCommandInterface',
    'DrydockWindowsWorkingCopyBlueprintImplementation' => 'DrydockBlueprintImplementation',
  ),
));
